package http_errors

const (
	BAD_EMAIL                = "BAD_EMAIL"
	BAD_PASSWORD             = "BAD_PASSWORD"
	COULD_NOT_CREATE_USER    = "COULD_NOT_CREATE_USER"
	COULD_NOT_GENERATE_TOKEN = "COULD_NOT_GENERATE_TOKEN"

	REVOKED_REFRESH_TOKEN = "REVOKED_REFRESH_TOKEN"
	BAD_REFRESH_TOKEN     = "BAD_REFRESH_TOKEN"
	BAD_EMAIL_TOKEN       = "BAD_EMAIL_TOKEN"
	BAD_ACCESS_TOKEN      = "BAD_ACCESS_TOKEN"
)
