package http_errors

const (
	CHARACTER_NOT_FOUND          = "CHARACTER_NOT_FOUND"
	COULD_NOT_UPDATE_CHARACTER   = "COULD_NOT_UPDATE_CHARACTER"
	CHARACTER_DELETE_NOT_ALLOWED = "CHARACTER_DELETE_NOT_ALLOWED"
	COULD_NOT_DELETE_CHARACTER   = "COULD_NOT_DELETE_CHARACTER"
)
