package http_errors

const (
	INVALID_DATA          = "INVALID_DATA"
	COULD_NOT_CREATE_ITEM = "COULD_NOT_CREATE_ITEM"
	ITEM_NOT_FOUND        = "ITEM_NOT_FOUND"
	COULD_NOT_EDIT_ITEM   = "COULD_NOT_EDIT_ITEM"
	COULD_NOT_DELETE_ITEM = "COULD_NOT_DELETE_ITEM"
	COULD_NOT_GET_ITEMS   = "COULD_NOT_GET_ITEMS"
)
