package http_errors

const (
	USER_NOT_FOUND = "USER_NOT_FOUND"
	COULD_NOT_EDIT_USER = "COULD_NOT_EDIT_USER"
	COULD_NOT_GET_USERS = "COULD_NOT_GET_USERS"
	COULD_NOT_DELETE_USER = "COULD_NOT_DELETE_USER"
)