# .air.toml
root = "."
tmp_dir = "tmp"
[build]
  cmd = "go build -o ./tmp/dnd ."
  bin = "./tmp/dnd"
  delay = 1000 # ms
  exclude_dir = ["static", "tmp", "vendor"]
  include_ext = ["go", "tpl", "tmpl", "html", "pug", "css", "js", "env"]
  exclude_regex = ["_test\\.go"]
  stop_on_error = true