# Build stage
FROM golang:1.20.4 as build
WORKDIR /dnd
COPY . .
RUN go mod download
RUN go build -o dnd-backend

# Production stage
FROM alpine:latest as production
ARG APP_NAME

ENV APP_NAME=$APP_NAME
# ENV POSTGRES_PASSWORD=$POSTGRES_PASSWORD
# ENV POSTGRES_USER=$POSTGRES_USER
# ENV POSTGRES_DB=$POSTGRES_DB
# ENV POSTGRES_HOST=$POSTGRES_HOST
# ENV POSTGRES_PORT=$POSTGRES_PORT
# ENV LOG_SQL=$LOG_SQL

# ENV JWT_SECRET=$JWT_SECRET

# ENV SMTP_FROM=$SMTP_FROM
# ENV SMTP_USER=$SMTP_USER
# ENV SMTP_PASSWORD=$SMTP_PASSWORD
# ENV SMTP_HOST=$SMTP_HOST
# ENV SMTP_PORT=$SMTP_PORT

# ENV BASE_URL=$BASE_URL
# ENV ALLOWED_ORIGINS=$ALLOWED_ORIGINS
# ENV PORT=$PORT

WORKDIR /dnd
COPY --from=build /dnd/dnd-backend ./
RUN ls | echo
CMD ./dnd-backend