version: '3.9'
services:
  webapp:
    build: "../webapp"
    depends_on:
      - backend
  backend:
    build: .
    depends_on:
      - redis
      - pg
  pg:
    image: postgres:alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
