FROM golang:alpine

ENV POSTGRES_PASSWORD=$POSTGRES_PASSWORD
ENV POSTGRES_USER=$POSTGRES_USER
ENV POSTGRES_DB=$POSTGRES_DB
ENV POSTGRES_HOST=$POSTGRES_HOST
ENV POSTGRES_PORT=$POSTGRES_PORT
ENV LOG_SQL=$LOG_SQL

ENV JWT_SECRET=$JWT_SECRET

ENV SMTP_FROM=$SMTP_FROM
ENV SMTP_USER=$SMTP_USER
ENV SMTP_PASSWORD=$SMTP_PASSWORD
ENV SMTP_HOST=$SMTP_HOST
ENV SMTP_PORT=$SMTP_PORT

ENV BASE_URL=$BASE_URL

WORKDIR /dnd
COPY . .
RUN go build -o dnd-backend
EXPOSE $PORT

CMD ./dnd-backend