package http_codes

const (
	USER_CREATED          = "USER_CREATED"
	LOGGED_IN             = "LOGGED_IN"
	TOKEN_REFRESHED       = "TOKEN_REFRESHED"
	REFRESH_TOKEN_REVOKED = "REFRESH_TOKEN_REVOKED"
	EMAIL_VERIFIED        = "EMAIL_VERIFIED"
	RECOVERY_EMAIL_SENT   = "RECOVERY_EMAIL_SENT"
	PASSWORD_CHANGED      = "PASSWORD_CHANGED"
)
