version: "3.9"
services:
  app:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
      args:
        NODE_VERSION: v18.20.4
        GO_VERSION: 1.22.6

    volumes:
      - ..:/workspace/dnd-backend
    command: sleep infinity
    network_mode: service:pg

  pg:
    image: postgres:alpine
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: dnd
      POSTGRES_DB: dnd

volumes:
  postgres-data:
