version: "3.9"
services:
  app:
    context: ..
    dockerfile: .devcontainer/Dockerfile
    args:
      NODE_VERSION: v18.12.1
      GO_VERSION: 1.20.5
  pg:
    image: postgres:alpine
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
